/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spendingtracker;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author adam-
 */
public class Data extends javax.swing.JFrame {
    
    private MainMenu main;

    /**
     * Creates new form Spending
     */
    public Data(MainMenu main) {
        initComponents();
        this.main = main;
        loadTable();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        lineGph = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        spendingTable = new javax.swing.JTable();
        lineGph1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lineGph.setText("Generate Graph");
        lineGph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lineGphActionPerformed(evt);
            }
        });

        spendingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Amount", "Category", "Balance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spendingTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(spendingTable);

        lineGph1.setText("Remove Spending Entry");
        lineGph1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lineGph1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lineGph1)
                .addGap(18, 18, 18)
                .addComponent(lineGph)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lineGph)
                    .addComponent(jButton1)
                    .addComponent(lineGph1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void loadTable(){
        
        String line = "";
        BufferedReader br = null;
         
        try {
            br = new BufferedReader(new FileReader(main.userName + "spending.csv"));
            DefaultTableModel tableModel = (DefaultTableModel) spendingTable.getModel();
            
            // clear rows
            tableModel.setRowCount(0);
            
            while ((line = br.readLine()) != null) {

                // use comma as separator
                String[] item = line.split(",");

                tableModel.addRow(new Object[]{item[1], item[0], item[2], item[3]});
            }
            
            br.close();

        } catch (FileNotFoundException e) {
            System.out.print("not found");
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    private void removeSpendingEntry(int index){
        DecimalFormat FORMAT = new DecimalFormat("0.00");
        
        try {
            BufferedReader br = new BufferedReader(new FileReader(main.userName + "spending.csv"));
            String stringToWrite = "";
            
            String line;
            
            int i = 0;
            double balanceChange = 0;
            
            while ((line = br.readLine()) != null){
                
                // if not the entry we want to remove, then add to string
                if (i > index){
                    // if i greater than index, modify balance
                    String[] parts = line.split(",");
                    
                    stringToWrite = stringToWrite + parts[0] + "," + parts[1] + "," + parts[2] + ",";
                    
                    // modify balance
                    
                    // get new balance
                    Double total = Double.parseDouble(parts[3]) + balanceChange;
                    
                    stringToWrite = stringToWrite + FORMAT.format(total) + "\n";
                    
                }else if (i != index){
                    stringToWrite = stringToWrite + line + "\n";
                } else{
                    balanceChange = -1*Double.parseDouble(line.split(",")[0]);
                }
                
                i++;
            }
            
            
            // create file writer, set append to FALSE, as we want to overwrite
            FileWriter writer = new FileWriter(main.userName + "spending.csv", false);
            
            // write string to file
            writer.write(stringToWrite);
            
            // close writer
            writer.close();
            
            
            
            br = new BufferedReader(new FileReader(main.userName + "balance.csv"));
            
            String oldBalance = br.readLine();
            
            String newBalance = FORMAT.format(Double.parseDouble(oldBalance) + balanceChange);
            
            // create file writer, set append to FALSE, as we want to overwrite
            writer = new FileWriter(main.userName + "balance.csv", false);
            
            // write updated balance
            writer.write(newBalance);
            
            // close writer
            writer.close();
            
            // update main menu
            main.updateBalance();
            
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
        
        
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lineGphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineGphActionPerformed
        Graphs Graph = new Graphs(main);
        Graph.setVisible(true);
    }//GEN-LAST:event_lineGphActionPerformed

    private void lineGph1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineGph1ActionPerformed
        // TODO when clicked, remove entry and redo table
        int rowSelected = spendingTable.getSelectedRow();
        
        // if a row is selected then remove
        if (rowSelected != -1){
            this.removeSpendingEntry(rowSelected);
            this.loadTable();
        }
    }//GEN-LAST:event_lineGph1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton lineGph;
    private javax.swing.JButton lineGph1;
    private javax.swing.JTable spendingTable;
    // End of variables declaration//GEN-END:variables
}
